[package]
name = "my-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
bytes = "1"
crossbeam = "0.8"
futures = "0.3"
tracing = "0.1.34"
